M48
; DRILL file {KiCad 8.0.6} date 2025-03-17T22:04:29-0600
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-03-17T22:04:29-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1280
%
G90
G05
T1
X4.9016Y-2.9528
X5.748Y-2.3819
X6.752Y-3.3661
T2
X6.365Y-2.0543
X6.865Y-2.0543
M30
